apply plugin: 'com.android.library'
apply plugin: 'org.jetbrains.kotlin.android'
apply plugin: 'expo-module-gradle-plugin'

androidComponents {
  beforeVariants(selector().all()) { variant ->
    variant.enable = variant.buildType != BuildType.RELEASE
  }
}

android {
  compileSdkVersion safeExtGet("compileSdkVersion", 35)
  namespace "expo.modules.clipboardnative"

  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 24)
  }

  lintOptions {
    abortOnError false
  }
}

repositories {
  mavenCentral()
}

dependencies {
  implementation project(':expo-modules-core')
}
